name: CI

on:
  push:
    branches:
      - main
      - "features/**"
  pull_request:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.1"

      - name: Install dependencies
        run: opam install . --deps-only --with-test --yes

      - name: Build
        run: opam exec -- dune build @all

      - name: Test
        run: opam exec -- dune runtest

      - name: Package build
        run: opam exec -- dune build -p transom

      - name: Lint opam file
        run: opam lint transom.opam
